Upgrade Ghost to 1.21.1
mmornati/docker-ghostblog pull request #25
Opened 2018-02-10 05:38 UTC by sr229

2018-02-10 09:23 UTC, mmornati requested changes
I think the build is not working anymore and the add of `exit 0` is just hiding the problem.
<img width="997" alt="capture d ecran 2018-02-10 a 10 21 34" src="https://user-images.githubusercontent.com/139323/36060559-6b8b0826-0e4c-11e8-990a-8b1b98eac588.png">

2018-02-10 09:23 UTC, mmornati commented on .travis.yml
> +    - exit 0
Strange to see that we must do this. In the Travis documentation there is

> The exit code of `after_success`, `after_failure`, `after_script` and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as a failure.

So I think we have to check why the aster script is not working correctly without putting an Exit 0.
I'm going to check the failure build of your PullRequest

2018-02-10 13:57 UTC, sr229 commented
@mmornati I think I triaged it on the root cause of failed builds:

- It seems that the reason it fails is because ghost does not permit usage of CLI via root, I had to install su-exec on the builder to force it to install using `node` user

2018-02-10 14:11 UTC, sr229 commented
I also downgraded to `6-alpine` since this is also the image used by official and it seems to work

2018-02-10 16:16 UTC, pascalandy commented
LGTM.

I would curious to know why node 8 I crashing.

2018-02-10 17:45 UTC, mmornati commented
No idea.... We migrated to node 8 long time ago and we never had problem. I will take a look this evening to the pull requests.

2018-02-10 19:03 UTC, mmornati approved these changes

2018-02-10 19:04 UTC, mmornati commented
I'm approving your changes but I will try to switch back to the latest node version.
Good Job and thanks :)

2018-02-10 19:04 UTC, merged

2018-02-11 03:11 UTC, pascalandy commented
Will work on it as well